### ISSUE TITLE
Scales with precision over 10 get hard to read

### ISSUE THREAD

**Issue by ORBAT** [phyver/VernierWheel#1]
I was adviced to start working on getting to 1/20th precision. When doing scales with precision of over 10, the numbers after 10 bunch up:

![example of 1/20 vernier](https://i.imgur.com/DE8pwTj.png)

Allowing an optional rotation offset for vernier numbers might help with this.

I might do a PR for this during the weekend

**Comment by phyver** [comment]
Option added, together with some minor improvements.
